package com.myspace.permitting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	//@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	//@org.kie.api.definition.type.Label(value = "Email Address")
	private java.lang.String emailAddress;
	//@org.kie.api.definition.type.Label(value = "Phone Number")
	private java.lang.String phoneNumber;
	//@org.kie.api.definition.type.Label(value = "Address")
	private java.lang.String address;

	public Applicant() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(java.lang.String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public java.lang.String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(java.lang.String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public Applicant(java.lang.String name, java.lang.String emailAddress,
			java.lang.String phoneNumber, java.lang.String address) {
		this.name = name;
		this.emailAddress = emailAddress;
		this.phoneNumber = phoneNumber;
		this.address = address;
	}

}